public with sharing class SomarContas {
    public static void somar(Integer um, Integer dois) {
        Integer soma = um + dois;
        System.debug('A soma do parametros é: ' + soma);
    }
    
    public static void somar(Integer um, Integer dois, Integer tres) {
        Integer soma = um + dois + tres;
        System.debug('A soma do parametros é: ' + soma);
    }

    public static void somar(Integer um, Integer dois, Integer tres, Integer quatro) {
        Integer soma = um + dois + tres + quatro;
        System.debug('A soma do parametros é: ' + soma);
    }


}